services:

  ollama:
    image: ollama/ollama:latest

    container_name: ollama

    restart: unless-stopped

    ports:
      - "${OLLAMA_PORT}:11434"

    volumes:
      - ollama-data:/root/.ollama

    environment:
      OLLAMA_KEEP_ALIVE: ${OLLAMA_KEEP_ALIVE}

    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities:
                - gpu

    healthcheck:
      test: ["CMD", "ollama", "list"]
      interval: 30s
      timeout: 10s
      retries: 5

    logging:
      driver: json-file
      options:
        max-size: "20m"
        max-file: "5"


  chatbot:
    build: .
    container_name: qa-chatbot
    restart: unless-stopped
    depends_on:
      ollama:
        condition: service_healthy
      postgres:
       condition: service_healthy
    ports:
      - "8501:8501"
    env_file:
      - .env
    environment:
      OLLAMA_HOST: http://ollama:11434
      DB_HOST: postgres
      DB_PORT: 5432
      DB_NAME: chatbot 
      DB_USER: chatbot
      DB_PASSWORD: chatbot 

  postgres:
    image: postgres:16

    container_name: postgres

    restart: unless-stopped

    environment:
      POSTGRES_DB: chatbot
      POSTGRES_USER: chatbot
      POSTGRES_PASSWORD: chatbot

    ports:
      - "5432:5432"

    volumes:
      - postgres-data:/var/lib/postgresql/data

    healthcheck:
      test: ["CMD-SHELL","pg_isready -U chatbot"]
      interval: 10s
      retries: 5


volumes:
  ollama-data:
  postgres-data:
